[tool.ruff]
line-length = 88  # Longitud de línea recomendada
target-version = "py311"  # O la versión de Python que uses

[tool.ruff.lint]
select = ["E", "F", "W", "I", "ANN"]  # Errores, fallos, advertencias y orden de imports
ignore = ["E501"]  # Ignorar advertencias por líneas largas (si usas Black)

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignorar imports sin usar en archivos __init__.py
